### ISSUE TITLE
No translation for α

### ISSUE THREAD

**Issue by mixos** [gschizas/RomanizeJava#1]
Χρησιμοποιώ eclipse Mars και προσπαθώ να μεταφράσω πχ το παπα ή πάπά ή σκέτο το α / ά.

Στο output παίρνω πάντα το ίδιο γράμμα που σημαίνει οτι γίνεται ignore. Αυτό δεν συμβαίνει με το ε,η,ι κλπ, μόνο με το α.

**Comment by gschizas** [comment]
Τι εννοείς; Το "α" (άλφα) γίνεται "a", όπως και το "ά" (τονούμενο άλφα). Τι περίμενες να συμβεί;

"παπα" &rArr; "papa"
"πάπά" &rArr; "papa"

**Comment by mixos** [comment]
Αυτό περίμενα να γίνει αλλά τελικά παραμένει α ελληνικό. Το έχω ξεπεράσει με απλό replace στο τέλος πριν το return απλά το αναφέρω. Χρησιμοποιώ eclipse mars με java 1.7

**Comment by gschizas** [comment]
Κάτι πρέπει να κάνεις λάθος, γιατί το έλεγξα και παίζει κανονικά. Δεν παίζει ρόλο τι IDE χρησιμοποιείς - το JAR είναι το ίδιο σε όλες τις περιπτώσεις.

Ανέβασα καινούρια έκδοση με assertion βασισμένα στο δικό σου test

**Comment by gschizas** [comment]
Turns out, you need to enable assertions for them to work. Also, indexOf is 0-based, not 1-based.
